### ISSUE TITLE
Bug: ERROR TypeError: n.getEmptyWarningTemplate is not a function

### ISSUE THREAD

**Issue by JakubEsterka** [zebzhao/Angular-QueryBuilder#67]
If you use the component in a production build (ng build --prod) I get this TypeError:

ERROR TypeError: n.getEmptyWarningTemplate is not a function
    at Object.eval [as updateDirectives] (VM8890 app.js:3)
    at Object.updateDirectives ...

It does not matter if I use the custom emptyMessage or not but this only happens in the newest version where the emptyMessage directive was added.

**Comment by zebzhao** [comment]
Can you test with the latest version 0.3.3? If it doesn't work, can you create a repo replicating this issue?

I am using Angular 6 and it seems to be working for me with the prod setting.

**Comment by JakubEsterka** [comment]
It seems to be working with the 0.3.3, my bad
